CREATE TABLE profanity_words (
     id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     word varchar(100) NOT NULL UNIQUE
         CHECK (length(trim(word)) > 0)
);

INSERT INTO profanity_words (word)
VALUES
    ('shit'),
    ('fuck'),
    ('idiot');