events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    upstream article_services {
        zone article_services 64k;
        server article-service:8080 resolve;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://article_services;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}